/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StockTransfer } from "./StockTransfer";
import { StockTransferCountArgs } from "./StockTransferCountArgs";
import { StockTransferFindManyArgs } from "./StockTransferFindManyArgs";
import { StockTransferFindUniqueArgs } from "./StockTransferFindUniqueArgs";
import { DeleteStockTransferArgs } from "./DeleteStockTransferArgs";
import { StockTransferService } from "../stockTransfer.service";
@graphql.Resolver(() => StockTransfer)
export class StockTransferResolverBase {
  constructor(protected readonly service: StockTransferService) {}

  async _stockTransfersMeta(
    @graphql.Args() args: StockTransferCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StockTransfer])
  async stockTransfers(
    @graphql.Args() args: StockTransferFindManyArgs
  ): Promise<StockTransfer[]> {
    return this.service.stockTransfers(args);
  }

  @graphql.Query(() => StockTransfer, { nullable: true })
  async stockTransfer(
    @graphql.Args() args: StockTransferFindUniqueArgs
  ): Promise<StockTransfer | null> {
    const result = await this.service.stockTransfer(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StockTransfer)
  async deleteStockTransfer(
    @graphql.Args() args: DeleteStockTransferArgs
  ): Promise<StockTransfer | null> {
    try {
      return await this.service.deleteStockTransfer(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
